# Этап 1 — сборка зависимостей
FROM python:3.12-slim AS builder
WORKDIR /app
COPY requirements.txt .
RUN pip install --user --no-cache-dir -r requirements.txt

# Этап 2 — финальный минимальный образ
FROM python:3.12-slim

WORKDIR /app

# Копируем только то, что нужно, и от пользователя root → non-root
COPY --from=builder /root/.local /root/.local
COPY app.py .

ENV PATH=/root/.local/bin:$PATH

EXPOSE 5000
USER 1000

CMD ["python", "app.py"]
